CREATE TABLE IF NOT EXISTS answer (
  id SERIAL NOT NULL PRIMARY KEY,
  order_number SMALLINT NOT NULL,
  correctness BOOL NOT NULL,
  liked_status BOOL NOT NULL DEFAULT FALSE,
  shared_facebook_link VARCHAR(256) DEFAULT NULL,
  shared_twitter_link VARCHAR(256) DEFAULT NULL,
  session_id INTEGER NOT NULL REFERENCES session (id) ON DELETE CASCADE,
  chosed_option_id INTEGER NOT NULL REFERENCES option (id) ON DELETE CASCADE,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW()
);
