CREATE TABLE IF NOT EXISTS option (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR(256) NOT NULL UNIQUE,
  description TEXT DEFAULT NULL,
  category_id INT NOT NULL REFERENCES category (id) ON DELETE CASCADE,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW()
);
