CREATE TABLE IF NOT EXISTS session (
  id SERIAL NOT NULL PRIMARY KEY,
  ip INET NOT NULL,
  device VARCHAR(256) NOT NULL,
  social_user_id INTEGER NOT NULL REFERENCES social_user (id) ON DELETE CASCADE,
  time_stamp TIMESTAMP NOT NULL DEFAULT NOW()
);
