from .db import *

class Task(Db):
    def __init__(self, connection):
        super().__init__(connection)

    def fetchByRandom(self):
        return self._fetch("""
            SELECT * FROM task
            WHERE is_active = TRUE
            LIMIT 1
        """)[0]

    def fetchByLabel(self, label):
        return self._fetch("""
            SELECT * FROM task
            WHERE label = %(label)s AND is_active = TRUE
            LIMIT 1
        """, {'label': label,})[0]

    def push(self, label, subjectId, optionIds):
        id = self._execute("""
            INSERT INTO task (label, is_active, description, subject_id)
            VALUES (%(label)s, TRUE, 'autogenerated', %(subject_id)s)
            RETURNING id
        """, {'label': label, 'subject_id': subjectId,}, True)
        for optionId in optionIds:
            self._execute("""
                INSERT INTO task_option (task_id, option_id)
                VALUES (%(task_id)s, %(option_id)s)
            """, {'task_id': id, 'option_id': optionId,}, False, False)
        self._commit()
        return id
