from yoyo import step

__depends__ = {}

steps = [
    step(
        '''
          INSERT INTO setting (name, value) VALUES
          ('option-count', '3'),
          ('effect-count', '2'),
          ('land-count', '6'),
          ('choose-period', '60'),
          ('task-rating-offset', '300'),
          ('task-novelty-period', '-3'),
          ('share-title', 'Fun quiz-game: reveal TRUE essence of image past various effects, filters and deformations.'),
          ('copyright-text', 'rect.io © 2018 all rights reserved'),
          ('disclaimer-text', '
This service is NOT INTENDED to offend or humiliate anyone.
Any resources placed on or generated by this service have exclusively entertaining nature,
and should not be interpret of in any other forms.
The only purpose of this service is ENTERTAINMENT and nothing else.
In the end, this is ONLY shaders. HAVE FUN!
          ')
        '''
    )
]
