// flow-typed signature: 0cfb528ff5fb4bcb07e2d39c4f7f12db
// flow-typed version: <<STUB>>/gl-react_v3.13.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gl-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gl-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gl-react/flow/gl-shader' {
  declare module.exports: any;
}

declare module 'gl-react/flow/invariant' {
  declare module.exports: any;
}

declare module 'gl-react/flow/lru' {
  declare module.exports: any;
}

declare module 'gl-react/flow/ndarray' {
  declare module.exports: any;
}

declare module 'gl-react/flow/typedarray-pool' {
  declare module.exports: any;
}

declare module 'gl-react/gl-react' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Bus' {
  declare module.exports: any;
}

declare module 'gl-react/lib/connectSize' {
  declare module.exports: any;
}

declare module 'gl-react/lib/copyShader' {
  declare module.exports: any;
}

declare module 'gl-react/lib/createSurface' {
  declare module.exports: any;
}

declare module 'gl-react/lib/genId' {
  declare module.exports: any;
}

declare module 'gl-react/lib/GLSL' {
  declare module.exports: any;
}

declare module 'gl-react/lib/helpers/disposable' {
  declare module.exports: any;
}

declare module 'gl-react/lib/helpers/drawNDArrayTexture' {
  declare module.exports: any;
}

declare module 'gl-react/lib/helpers/invariantNoDependentsLoop' {
  declare module.exports: any;
}

declare module 'gl-react/lib/helpers/log' {
  declare module.exports: any;
}

declare module 'gl-react/lib/index' {
  declare module.exports: any;
}

declare module 'gl-react/lib/LinearCopy' {
  declare module.exports: any;
}

declare module 'gl-react/lib/NearestCopy' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Node' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Shaders' {
  declare module.exports: any;
}

declare module 'gl-react/lib/TextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react/lib/TextureLoaderNDArray' {
  declare module.exports: any;
}

declare module 'gl-react/lib/TextureLoaderRawObject' {
  declare module.exports: any;
}

declare module 'gl-react/lib/TextureLoaders' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Uniform' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Visitor' {
  declare module.exports: any;
}

declare module 'gl-react/lib/VisitorLogger' {
  declare module.exports: any;
}

declare module 'gl-react/lib/Visitors' {
  declare module.exports: any;
}

declare module 'gl-react/src/Bus' {
  declare module.exports: any;
}

declare module 'gl-react/src/connectSize' {
  declare module.exports: any;
}

declare module 'gl-react/src/copyShader' {
  declare module.exports: any;
}

declare module 'gl-react/src/createSurface' {
  declare module.exports: any;
}

declare module 'gl-react/src/genId' {
  declare module.exports: any;
}

declare module 'gl-react/src/GLSL' {
  declare module.exports: any;
}

declare module 'gl-react/src/helpers/disposable' {
  declare module.exports: any;
}

declare module 'gl-react/src/helpers/drawNDArrayTexture' {
  declare module.exports: any;
}

declare module 'gl-react/src/helpers/invariantNoDependentsLoop' {
  declare module.exports: any;
}

declare module 'gl-react/src/helpers/log' {
  declare module.exports: any;
}

declare module 'gl-react/src/index' {
  declare module.exports: any;
}

declare module 'gl-react/src/LinearCopy' {
  declare module.exports: any;
}

declare module 'gl-react/src/NearestCopy' {
  declare module.exports: any;
}

declare module 'gl-react/src/Node' {
  declare module.exports: any;
}

declare module 'gl-react/src/Shaders' {
  declare module.exports: any;
}

declare module 'gl-react/src/TextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react/src/TextureLoaderNDArray' {
  declare module.exports: any;
}

declare module 'gl-react/src/TextureLoaderRawObject' {
  declare module.exports: any;
}

declare module 'gl-react/src/TextureLoaders' {
  declare module.exports: any;
}

declare module 'gl-react/src/Uniform' {
  declare module.exports: any;
}

declare module 'gl-react/src/Visitor' {
  declare module.exports: any;
}

declare module 'gl-react/src/VisitorLogger' {
  declare module.exports: any;
}

declare module 'gl-react/src/Visitors' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gl-react/flow/gl-shader.js' {
  declare module.exports: $Exports<'gl-react/flow/gl-shader'>;
}
declare module 'gl-react/flow/invariant.js' {
  declare module.exports: $Exports<'gl-react/flow/invariant'>;
}
declare module 'gl-react/flow/lru.js' {
  declare module.exports: $Exports<'gl-react/flow/lru'>;
}
declare module 'gl-react/flow/ndarray.js' {
  declare module.exports: $Exports<'gl-react/flow/ndarray'>;
}
declare module 'gl-react/flow/typedarray-pool.js' {
  declare module.exports: $Exports<'gl-react/flow/typedarray-pool'>;
}
declare module 'gl-react/gl-react.js' {
  declare module.exports: $Exports<'gl-react/gl-react'>;
}
declare module 'gl-react/lib/Bus.js' {
  declare module.exports: $Exports<'gl-react/lib/Bus'>;
}
declare module 'gl-react/lib/connectSize.js' {
  declare module.exports: $Exports<'gl-react/lib/connectSize'>;
}
declare module 'gl-react/lib/copyShader.js' {
  declare module.exports: $Exports<'gl-react/lib/copyShader'>;
}
declare module 'gl-react/lib/createSurface.js' {
  declare module.exports: $Exports<'gl-react/lib/createSurface'>;
}
declare module 'gl-react/lib/genId.js' {
  declare module.exports: $Exports<'gl-react/lib/genId'>;
}
declare module 'gl-react/lib/GLSL.js' {
  declare module.exports: $Exports<'gl-react/lib/GLSL'>;
}
declare module 'gl-react/lib/helpers/disposable.js' {
  declare module.exports: $Exports<'gl-react/lib/helpers/disposable'>;
}
declare module 'gl-react/lib/helpers/drawNDArrayTexture.js' {
  declare module.exports: $Exports<'gl-react/lib/helpers/drawNDArrayTexture'>;
}
declare module 'gl-react/lib/helpers/invariantNoDependentsLoop.js' {
  declare module.exports: $Exports<'gl-react/lib/helpers/invariantNoDependentsLoop'>;
}
declare module 'gl-react/lib/helpers/log.js' {
  declare module.exports: $Exports<'gl-react/lib/helpers/log'>;
}
declare module 'gl-react/lib/index.js' {
  declare module.exports: $Exports<'gl-react/lib/index'>;
}
declare module 'gl-react/lib/LinearCopy.js' {
  declare module.exports: $Exports<'gl-react/lib/LinearCopy'>;
}
declare module 'gl-react/lib/NearestCopy.js' {
  declare module.exports: $Exports<'gl-react/lib/NearestCopy'>;
}
declare module 'gl-react/lib/Node.js' {
  declare module.exports: $Exports<'gl-react/lib/Node'>;
}
declare module 'gl-react/lib/Shaders.js' {
  declare module.exports: $Exports<'gl-react/lib/Shaders'>;
}
declare module 'gl-react/lib/TextureLoader.js' {
  declare module.exports: $Exports<'gl-react/lib/TextureLoader'>;
}
declare module 'gl-react/lib/TextureLoaderNDArray.js' {
  declare module.exports: $Exports<'gl-react/lib/TextureLoaderNDArray'>;
}
declare module 'gl-react/lib/TextureLoaderRawObject.js' {
  declare module.exports: $Exports<'gl-react/lib/TextureLoaderRawObject'>;
}
declare module 'gl-react/lib/TextureLoaders.js' {
  declare module.exports: $Exports<'gl-react/lib/TextureLoaders'>;
}
declare module 'gl-react/lib/Uniform.js' {
  declare module.exports: $Exports<'gl-react/lib/Uniform'>;
}
declare module 'gl-react/lib/Visitor.js' {
  declare module.exports: $Exports<'gl-react/lib/Visitor'>;
}
declare module 'gl-react/lib/VisitorLogger.js' {
  declare module.exports: $Exports<'gl-react/lib/VisitorLogger'>;
}
declare module 'gl-react/lib/Visitors.js' {
  declare module.exports: $Exports<'gl-react/lib/Visitors'>;
}
declare module 'gl-react/src/Bus.js' {
  declare module.exports: $Exports<'gl-react/src/Bus'>;
}
declare module 'gl-react/src/connectSize.js' {
  declare module.exports: $Exports<'gl-react/src/connectSize'>;
}
declare module 'gl-react/src/copyShader.js' {
  declare module.exports: $Exports<'gl-react/src/copyShader'>;
}
declare module 'gl-react/src/createSurface.js' {
  declare module.exports: $Exports<'gl-react/src/createSurface'>;
}
declare module 'gl-react/src/genId.js' {
  declare module.exports: $Exports<'gl-react/src/genId'>;
}
declare module 'gl-react/src/GLSL.js' {
  declare module.exports: $Exports<'gl-react/src/GLSL'>;
}
declare module 'gl-react/src/helpers/disposable.js' {
  declare module.exports: $Exports<'gl-react/src/helpers/disposable'>;
}
declare module 'gl-react/src/helpers/drawNDArrayTexture.js' {
  declare module.exports: $Exports<'gl-react/src/helpers/drawNDArrayTexture'>;
}
declare module 'gl-react/src/helpers/invariantNoDependentsLoop.js' {
  declare module.exports: $Exports<'gl-react/src/helpers/invariantNoDependentsLoop'>;
}
declare module 'gl-react/src/helpers/log.js' {
  declare module.exports: $Exports<'gl-react/src/helpers/log'>;
}
declare module 'gl-react/src/index.js' {
  declare module.exports: $Exports<'gl-react/src/index'>;
}
declare module 'gl-react/src/LinearCopy.js' {
  declare module.exports: $Exports<'gl-react/src/LinearCopy'>;
}
declare module 'gl-react/src/NearestCopy.js' {
  declare module.exports: $Exports<'gl-react/src/NearestCopy'>;
}
declare module 'gl-react/src/Node.js' {
  declare module.exports: $Exports<'gl-react/src/Node'>;
}
declare module 'gl-react/src/Shaders.js' {
  declare module.exports: $Exports<'gl-react/src/Shaders'>;
}
declare module 'gl-react/src/TextureLoader.js' {
  declare module.exports: $Exports<'gl-react/src/TextureLoader'>;
}
declare module 'gl-react/src/TextureLoaderNDArray.js' {
  declare module.exports: $Exports<'gl-react/src/TextureLoaderNDArray'>;
}
declare module 'gl-react/src/TextureLoaderRawObject.js' {
  declare module.exports: $Exports<'gl-react/src/TextureLoaderRawObject'>;
}
declare module 'gl-react/src/TextureLoaders.js' {
  declare module.exports: $Exports<'gl-react/src/TextureLoaders'>;
}
declare module 'gl-react/src/Uniform.js' {
  declare module.exports: $Exports<'gl-react/src/Uniform'>;
}
declare module 'gl-react/src/Visitor.js' {
  declare module.exports: $Exports<'gl-react/src/Visitor'>;
}
declare module 'gl-react/src/VisitorLogger.js' {
  declare module.exports: $Exports<'gl-react/src/VisitorLogger'>;
}
declare module 'gl-react/src/Visitors.js' {
  declare module.exports: $Exports<'gl-react/src/Visitors'>;
}
