version: '3'

services:
    db:
        build: ./db
        command: postgres -c config_file=/etc/postgresql/pgsql.conf
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data/db:/var/lib/postgresql/data:rw
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'

    cache:
        build:
            context: ./cache
            args:
                - REDIS_PASSWORD
        command: redis-server /etc/redis/redis.conf
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data/cache:/data:rw
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'

    api:
        build:
            context: ./../
            dockerfile: docker/api/Dockerfile
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data:/var/rere1:ro
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'
