version: '3'
services:
    database:
        build: ./database
        command: postgres -c config_file=/etc/pgsql.conf
        restart: on-failure
        volumes:
            - ./../dump/pgdata:/var/lib/postgresql/data
            - ./../dump/logs:/var/logs
            - ./../dump/sql:/docker-entrypoint-initdb.d
        environment:
            POSTGRES_USER: default
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rectio
    cache:
        build: ./cache
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: on-failure
        volumes:
            - ./../dump/logs:/var/logs
    api:
        build:
            context: ./../
            dockerfile: docker/api/Dockerfile
        restart: on-failure
        volumes:
            - ./../dump/logs:/var/logs
        depends_on:
            - database
            - cache