version: '3'

services:
    db:
        build:
            context: ./db
            args:
                - SHARED_BUFFERS_MEMORY
                - EFFECTIVE_CACHE_SIZE_MEMORY
                - MAINTANCE_WORK_MEMORY
                - WORK_MEMORY
        command: postgres -c config_file=/etc/postgresql/pgsql.conf
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data/db:/var/lib/postgresql/data:rw
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'
        ports:
            - 55555:5432

    storage:
        build:
            context: ./storage
            args:
                - STORAGE_PASSWORD
        command: redis-server /etc/redis/redis.conf
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data/storage:/data:rw
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'
        ports:
            - 33333:6379

    cache:
        build:
            context: ./cache
            args:
                - CACHE_PASSWORD
                - CACHE_MEMORY_LIMIT
        command: redis-server /etc/redis/redis.conf
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'
        ports:
            - 11111:6379

    wsgi:
        build:
            context: ./../
            dockerfile: docker/wsgi/Dockerfile
            args:
                - API_INITIALIZE_MODE
        env_file:
            - ./.env
        restart: on-failure
        volumes:
            - ./../dump/data:/var/rere1:ro
            - ./../dump/log:/var/logs:rw
        logging:
            driver: json-file
            options:
                max-size: '100m'
                max-file: '10'
