version: '3'
services:
    database:
        image: postgres
        # most retarted image ever
        # command: postgres -c config_file=/etc/pgsql.conf
        restart: on-failure
        networks: 
            - net
        volumes:
            - ./database/pgsql.conf:/etc/pgsql.conf
            - ./../dump/pgdata:/var/lib/postgresql/data
            - ./../dump/logs:/var/logs
        environment:
            POSTGRES_USER: default
            POSTGRES_PASSWORD: password
            POSTGRES_DB: rectio
    cache:
        build: ./cache
        restart: on-failure
        networks: 
            - net
        volumes:
            - ./../dump/logs:/var/logs
    api:
        build:
            context: ./../
            dockerfile: docker/api/Dockerfile
        restart: on-failure
        networks:
            - net
        volumes:
            - ./../dump/logs:/var/logs
        depends_on:
            - database
            - cache
    proxy:
        build: ./proxy
        restart: on-failure
        networks:
            - net
        ports:
            - 80:80
        volumes:
            - ./../dump/logs:/var/logs
        depends_on:
            - api
networks:
    net:
        driver: bridge