class Constant:
    SETTING_MAIL_USERNAME = 'MAIL_USERNAME'

    SETTING_TOKEN_TIMEOUT = 'TOKEN_TIMEOUT'
    SETTING_IDENTITY_TIMEOUT = 'IDENTITY_TIMEOUT'
    SETTING_SESSION_DAILY_LIMIT = 'SESSION_DAILY_LIMIT'

    SETTING_MAX_RECONNECTION_TRY = 'MAX_RECONNECTION_TRY'
    SETTING_DEFAULT_SLEEP_TIME = 'DEFAULT_SLEEP_TIME'

    SETTING_OPTION_COUNT = 'OPTION_COUNT'
    SETTING_EFFECT_COUNT = 'EFFECT_COUNT'
    SETTING_LAND_COUNT = 'LAND_COUNT'
    SETTING_TABLE_SIZE = 'TABLE_SIZE'

    SETTING_SMALL_SCORE_UNIT = 'SMALL_SCORE_UNIT'
    SETTING_BIG_SCORE_UNIT = 'BIG_SCORE_UNIT'
    SETTING_SHARE_FREEBIE_UNIT = 'SHARE_FREEBIE_UNIT'
    SETTING_FREEBIE_GIFT_THRESHOLD = 'FREEBIE_GIFT_THRESHOLD'
    SETTING_MAX_SCORE_FACTOR = 'MAX_SCORE_FACTOR'

    SETTING_ROLL_BY_RATING = 'ROLL_BY_RATING'
    SETTING_ROLL_BY_RANDOM = 'ROLL_BY_RANDOM'
    SETTING_ROLL_BY_NOVELTY = 'ROLL_BY_NOVELTY'

    RIGID_CONNECTION_LIMIT = '3/second;300/minute;30000/hour;3000000/day'
    RAREFIED_CONNECTION_LIMIT = '3/second;30/minute;300/hour;3000/day'

    NORMAL_HASH_SIZE = 128
    VIEW_HASH_SIZE = 8

    DEFAULT_CACHE_EXPIRE = 86400

    DEFAULT_GENERATE_COUNT = 1000

    DAY_COUNT_SINGLE = 1
    DAY_COUNT_WEEK = 7
    DAY_COUNT_MONTH = 30
