class Constant:
    SETTING_MAX_RECONNECTION_TRY = 'MAX_RECONNECTION_TRY'
    SETTING_DEFAULT_SLEEP_TIME = 'DEFAULT_SLEEP_TIME'

    SETTING_TOKEN_TIMEOUT = 'TOKEN_TIMEOUT'
    SETTING_IDENTITY_TIMEOUT = 'IDENTITY_TIMEOUT'
    SETTING_SESSION_DAILY_LIMIT = 'SESSION_DAILY_LIMIT'

    SETTING_MAIL_USERNAME = 'MAIL_USERNAME'

    SETTING_INTEGRITY = 'INTEGRITY'
    SETTING_ADMIN_ALIAS = 'ADMIN_ALIAS'

    SETTING_OPTION_COUNT = 'OPTION_COUNT'
    SETTING_EFFECT_COUNT = 'EFFECT_COUNT'
    SETTING_HOME_LIST_SIZE = 'HOME_LIST_SIZE'
    SETTING_RATING_TABLE_SIZE = 'RATING_TABLE_SIZE'
    SETTING_MAX_SCORE_FACTOR = 'MAX_SCORE_FACTOR'
    SETTING_SMALL_SCORE_UNIT = 'SMALL_SCORE_UNIT'
    SETTING_BIG_SCORE_UNIT = 'BIG_SCORE_UNIT'
    SETTING_SHARE_FREEBIE_UNIT = 'SHARE_FREEBIE_UNIT'
    SETTING_FREEBIE_GIFT_THRESHOLD = 'FREEBIE_GIFT_THRESHOLD'

    SETTING_ROLL_BY_RATING = 'ROLL_BY_RATING'
    SETTING_ROLL_BY_RANDOM = 'ROLL_BY_RANDOM'
    SETTING_ROLL_BY_NOVELTY = 'ROLL_BY_NOVELTY'

    RIGID_CONNECTION_LIMIT = '10/second;1000/minute;100000/hour;10000000/day'
    RAREFIED_CONNECTION_LIMIT = '10/second;100/minute;1000/hour;10000/day'

    NORMAL_HASH_SIZE = 128
    VIEW_HASH_SIZE = 8

    DEFAULT_CACHE_EXPIRE = 86400

    DEFAULT_TASK_COUNT = 1000

    DAY_COUNT_SINGLE = 1
    DAY_COUNT_WEEK = 7
    DAY_COUNT_MONTH = 30
