// flow-typed signature: 2f113b9c38d473413168cf06d5217919
// flow-typed version: <<STUB>>/gl-react-image_v3.13.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gl-react-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gl-react-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gl-react-image/example/src/App' {
  declare module.exports: any;
}

declare module 'gl-react-image/example/src/App.test' {
  declare module.exports: any;
}

declare module 'gl-react-image/example/src/index' {
  declare module.exports: any;
}

declare module 'gl-react-image/example/src/registerServiceWorker' {
  declare module.exports: any;
}

declare module 'gl-react-image/example/src/syncLocationHashQuery' {
  declare module.exports: any;
}

declare module 'gl-react-image/lib/index' {
  declare module.exports: any;
}

declare module 'gl-react-image/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gl-react-image/example/src/App.js' {
  declare module.exports: $Exports<'gl-react-image/example/src/App'>;
}
declare module 'gl-react-image/example/src/App.test.js' {
  declare module.exports: $Exports<'gl-react-image/example/src/App.test'>;
}
declare module 'gl-react-image/example/src/index.js' {
  declare module.exports: $Exports<'gl-react-image/example/src/index'>;
}
declare module 'gl-react-image/example/src/registerServiceWorker.js' {
  declare module.exports: $Exports<'gl-react-image/example/src/registerServiceWorker'>;
}
declare module 'gl-react-image/example/src/syncLocationHashQuery.js' {
  declare module.exports: $Exports<'gl-react-image/example/src/syncLocationHashQuery'>;
}
declare module 'gl-react-image/lib/index.js' {
  declare module.exports: $Exports<'gl-react-image/lib/index'>;
}
declare module 'gl-react-image/src/index.js' {
  declare module.exports: $Exports<'gl-react-image/src/index'>;
}
