// flow-typed signature: 714cc9358a9a0b5ae151e5935fa93905
// flow-typed version: <<STUB>>/gl-react-dom_v3.13.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gl-react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gl-react-dom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gl-react-dom/gl-react-dom' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/CanvasTextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/getContext' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/GLViewDOM' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/ImageTextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/index' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/legacy' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/loseGL' {
  declare module.exports: any;
}

declare module 'gl-react-dom/lib/VideoTextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/CanvasTextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/getContext' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/GLViewDOM' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/ImageTextureLoader' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/index' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/legacy' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/loseGL' {
  declare module.exports: any;
}

declare module 'gl-react-dom/src/VideoTextureLoader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gl-react-dom/gl-react-dom.js' {
  declare module.exports: $Exports<'gl-react-dom/gl-react-dom'>;
}
declare module 'gl-react-dom/lib/CanvasTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/CanvasTextureLoader'>;
}
declare module 'gl-react-dom/lib/getContext.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/getContext'>;
}
declare module 'gl-react-dom/lib/GLViewDOM.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/GLViewDOM'>;
}
declare module 'gl-react-dom/lib/ImageTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/ImageTextureLoader'>;
}
declare module 'gl-react-dom/lib/index.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/index'>;
}
declare module 'gl-react-dom/lib/legacy.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/legacy'>;
}
declare module 'gl-react-dom/lib/loseGL.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/loseGL'>;
}
declare module 'gl-react-dom/lib/VideoTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/lib/VideoTextureLoader'>;
}
declare module 'gl-react-dom/src/CanvasTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/src/CanvasTextureLoader'>;
}
declare module 'gl-react-dom/src/getContext.js' {
  declare module.exports: $Exports<'gl-react-dom/src/getContext'>;
}
declare module 'gl-react-dom/src/GLViewDOM.js' {
  declare module.exports: $Exports<'gl-react-dom/src/GLViewDOM'>;
}
declare module 'gl-react-dom/src/ImageTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/src/ImageTextureLoader'>;
}
declare module 'gl-react-dom/src/index.js' {
  declare module.exports: $Exports<'gl-react-dom/src/index'>;
}
declare module 'gl-react-dom/src/legacy.js' {
  declare module.exports: $Exports<'gl-react-dom/src/legacy'>;
}
declare module 'gl-react-dom/src/loseGL.js' {
  declare module.exports: $Exports<'gl-react-dom/src/loseGL'>;
}
declare module 'gl-react-dom/src/VideoTextureLoader.js' {
  declare module.exports: $Exports<'gl-react-dom/src/VideoTextureLoader'>;
}
