version: '3'
services:
    client:
        build:
            context: ./../
            dockerfile: docker/client/Dockerfile
        restart: on-failure
        volumes:
            - ./../dump/images/:/var/images
            - ./../dump/logs:/var/logs
        ports:
            - 80:80
            - 443:443
